version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "{DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "./src:/var/www/html"

  ftp:
    build:
      context: ./vsftpd
      args:
        - USER_ID=33
        - GROUP_ID=33
    ports:
      - "20:20"
      - "21:21"
      - "21100-21110:21100-21110"
    environment:
      FTP_PASS: "${FTP_PASSWORD}"
      FTP_USER: "${COMPOSE_PROJECT_NAME}"
      LOCAL_UMASK: 022
      LOG_STDOUT: "/var/log/vsftpd/vsftpd.log"
    volumes:
      - "./src:/home/vsftpd/${COMPOSE_PROJECT_NAME}"

volumes:
    db_data: {}
