version: '3.3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "{DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "${SRC_PATH}:/var/www/html"

  ftp:
    build:
      context: ./vsftpd
      args:
        - "USER_ID=${SRC_OWNER_UID}"
        - "GROUP_ID=${SRC_OWNER_GID}"
    ports:
      - "${VSFTPD_HOST_DATA_PORT}:20"
      - "${VSFTPD_HOST_LISTEN_PORT}:21"
      - "${VSFTPD_HOST_PASV_DATA_PORT_RANGE}:21100-21110"
    restart: unless-stopped
    environment:
      FTP_PASS: "${FTP_PASSWORD}"
      FTP_USER: "${COMPOSE_PROJECT_NAME}"
      LOCAL_UMASK: 022
      LOG_STDOUT: "/var/log/vsftpd/vsftpd.log"
    volumes:
      - "${SRC_PATH}:/home/vsftpd/${COMPOSE_PROJECT_NAME}"

volumes:
    db_data: {}
